/** Declaration file generated by dts-gen */
declare module 'react-reveal' {
  export default interface ReactReveal {}
}

declare module 'react-reveal/Fade' {
  import React from 'react';

  export default React.Component;
}
